### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by whitelynx** [jdiamond/discoverable#1]
Tagging releases will make it easier to find changes since a given release, and will also populate the "Releases" tab on GitHub.

Also, in order to simplify committing and tagging releases for node packages, `npm` has a [`version` command](https://docs.npmjs.com/cli/version) I've started using recently, which bumps the version in `package.json` and, if run in a git repo, create a version commit and tag.

**Comment by Morgul** [comment]
:+1: 

This project is exactly what I need for several projects, and it works great, so thanks a lot! It would, however, be nice to see the versions a little more formalized, as suggested here.

**Comment by jdiamond** [comment]
OK, thanks for the tips. I'll look into it and start tagging all releases. I didn't realize anybody was using it besides me!

**Comment by jdiamond** [comment]
Just gave `npm version` a try. Will use it from now on. Thanks again for the tips.
